urls: "[{ url: 'http://dev.api.yas.local.com/product/v3/api-docs', name: 'Product' },
      { url: 'http://dev.api.yas.local.com/media/v3/api-docs', name: 'Media' },
      { url: 'http://dev.api.yas.local.com/customer/v3/api-docs', name: 'Customer' }, 
      { url: 'http://dev.api.yas.local.com/cart/v3/api-docs', name: 'Cart'},
      { url: 'http://dev.api.yas.local.com/rating/v3/api-docs', name: 'Rating' }, 
      { url: 'http://dev.api.yas.local.com/order/v3/api-docs', name: 'Order'},
      { url: 'http://dev.api.yas.local.com/payment/v3/api-docs', name: 'Payment'},
      { url: 'http://dev.api.yas.local.com/location/v3/api-docs', name: 'Location'}, 
      { url: 'http://dev.api.yas.local.com/inventory/v3/api-docs', name: 'Inventory'},
      { url: 'http://dev.api.yas.local.com/tax/v3/api-docs', name: 'Tax' },
      { url: 'http://dev.api.yas.local.com/promotion/v3/api-docs', name: 'Promotion'},
      { url: 'http://dev.api.yas.local.com/search/v3/api-docs', name: 'Search'}]"

ingress:
  host: dev.api.yas.local.com
  hosts:
    - host: dev.api.yas.local.com
      paths:
        - path: /swagger-ui
          pathType: ImplementationSpecific
        - path: /product
          pathType: Prefix
        - path: /media
          pathType: Prefix
        - path: /customer
          pathType: Prefix
        - path: /cart
          pathType: Prefix
        - path: /rating
          pathType: Prefix
        - path: /order
          pathType: Prefix
        - path: /payment
          pathType: Prefix
        - path: /location
          pathType: Prefix
        - path: /inventory
          pathType: Prefix
        - path: /tax
          pathType: Prefix
        - path: /promotion
          pathType: Prefix
        - path: /search
          pathType: Prefix