apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-frontend-services
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # Định nghĩa service, tên param của Helm và domain tương ứng
          - service: backoffice-bff
            wave: "3"
            
          - service: storefront-bff
            wave: "3"
            
          - service: swagger-ui
            wave: "3"
          
          - service: backoffice-ui
            wave: "2" 
            
          - service: storefront-ui
            wave: "2"

  template:
    metadata:
      name: '{{service}}-dev'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "{{wave}}" # Đọc wave từ biến để đảm bảo thứ tự
    spec:
      project: default
      source:
        repoURL: 'https://github.com/thanhdatttt/DevOps-Project.git'
        targetRevision: main
        path: 'k8s/charts/{{service}}'
        helm:
          valueFiles:
            - values-dev.yaml 
          parameters:
            - name: ui.image.pullPolicy
              value: Always
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
