hostname: identity.yas.local.com
backofficeRedirectUrlDev: http://dev.backoffice.yas.local.com
backofficeRedirectUrlStaging: http://staging.backoffice.yas.local.com
storefrontRedirectUrlDev: http://dev.storefront.yas.local.com
storefrontRedirectUrlStaging: http://staging.storefront.yas.local.com
postgresql:
  username: yasadminuser
  password: admin

bootstrapAdmin:
  username: admin
  password: admin