apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/thanhdatttt/DevOps-Project.git'
    path: k8s/argo  # Points to the folder holding your 4 AppSets
    targetRevision: feat/argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true