apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  yas.server: |
    yas.local.com:53 {
      errors
      rewrite stop {
        name exact identity.yas.local.com keycloak-service.keycloak.svc.cluster.local
        answer name keycloak-service.keycloak.svc.cluster.local identity.yas.local.com
      }
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
      }
      cache 30
    }
