apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devops-project-services
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/thanhdatttt/DevOps-Project.git'
        revision: feat/argocd
        directories:
          - path: k8s/charts/* # Chỉ quét các folder bên trong k8s/charts/
  template:
    metadata:
      name: '{{path.basename}}' # Tên App sẽ là tên service (ví dụ: tax-service)
      annotations:
        # Wave 5 ensures ALL infrastructure (Databases, Kafka, Operators) is running first!
        argocd.argoproj.io/sync-wave: "5"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/thanhdatttt/DevOps-Project.git'
        targetRevision: feat/ar
        path: '{{path}}' # Đường dẫn chính xác đến từng chart
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc # Deploy vào cụm hiện tại
        namespace: dev-env
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true