prometheus:
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - prometheus.yas.local.com
    paths:
      - /
    pathType: Prefix
  prometheusSpec:
    enableRemoteWriteReceiver: true
