apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
spec:
  mode: deployment
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.90.0
  ports:
    - name: loki
      port: 3500
      protocol: TCP
      targetPort: 3500
  config: |
    {{ toYaml .Values.opentelemetryCollectorConfig | nindent 4 }}