apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-sidecar-podmonitor-dev
  namespace: observability
  labels:
    app: envoy-sidecar-podmonitor
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - dev
  podMetricsEndpoints:
    - path: /stats/prometheus
      targetPort: 15020
      interval: 15s
      scheme: http
  selector: {}
