backend:
  image:
    repository: ghcr.io/thanhdatttt/yas-sampledata
    tag: staging

  nameOverride: sampledata
  fullnameOverride: sampledata
  databaseName: sampledata
  ingress:
    enabled: false